models/Forwarder.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "forwarder".
 *
 * @property string $id
 * @property string $kd_fw
 * @property string $nm_fw
 * @property string $tlp
 * @property string $qq
 * @property string $wechat
 * @property string $created_at
 */
class Forwarder extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'forwarder';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kd_fw', 'nm_fw', 'tlp', 'wechat'], 'default'],
            [['created_at'], 'safe'],
            [['kd_fw', 'nm_fw', 'tlp', 'qq', 'wechat'], 'string', 'max' => 150],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kd_fw' => 'Kd Fw',
            'nm_fw' => 'Name',
            'tlp' => 'Tlp',
            'qq' => 'Qq',
            'wechat' => 'Wechat',
            'created_at' => 'Created At',
        ];
    }
}

controllers/ForwarderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Forwarder;
use app\models\ForwarderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use app\components\Help;


/**
 * ForwarderController implements the CRUD actions for Forwarder model.
 */
class ForwarderController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Forwarder models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ForwarderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Forwarder model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Forwarder model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Forwarder();

        $user=Yii::$app->user->identity;
        $data=[];
        $data['user']=$user;
        $data['model']=$model;

            
        $r=Yii::$app->request->post('Forwarder');
        if ($r!= null) {
            $model->kd_fw=Help::inisial($r['nm_fw']);
            $model->nm_fw=$r['nm_fw'];
            $model->tlp=$r['tlp'];
            $model->qq=$r['qq'];
            $model->wechat=$r['wechat'];
            $model->store_id=$user->store_id;
            
            if($model->save()){
                $pesan=['pesan'=>'Data Berhasil di tambahkan !','status'=>1];
            }else{
                $pesan=['pesan'=>'Data gagal di tambahkan !','status'=>0];
            }
            echo json_encode($pesan);
        } else {
            return $this->renderPartial('_form', $data);
        };
    }

    /**
     * Updates an existing Forwarder model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

       
        $user=Yii::$app->user->identity;
        $data=[];
        $data['user']=$user;
        $data['model']=$model;

            
        $r=Yii::$app->request->post('Forwarder');
        if ($r!= null) {
            $model->kd_fw=Help::inisial($r['nm_fw']);
            $model->nm_fw=$r['nm_fw'];
            $model->tlp=$r['tlp'];
            $model->qq=$r['qq'];
            $model->wechat=$r['wechat'];
            
            if($model->save()){
                $pesan=['pesan'=>'Data Berhasil di perbarui !','status'=>1];
            }else{
                $pesan=['pesan'=>'Data gagal di perbarui !','status'=>0];
            }
            echo json_encode($pesan);
        } else {
            return $this->renderPartial('_form', $data);
        };
    }

    /**
     * Deletes an existing Forwarder model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        // return $this->redirect(['index']);
    }

    /**
     * Finds the Forwarder model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Forwarder the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Forwarder::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/forwarder/_form.php
<?php
    use yii\helpers\Url;
    use yii\helpers\Html;
    use yii\helpers\ArrayHelper;

    use app\models\Role;
    
?>

<form class="form-horizontal" id="form_fw" action="<?=($model->isNewRecord) ? Url::toRoute('forwarder/create') : Url::toRoute('forwarder/update').'/'.$model['id']; ?>" role="form">
    <div class="form-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="Forwarder[nm_fw]" value="<?=$model['nm_fw']?>" placeholder="Nama Forwarder" required="required">
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="Forwarder[tlp]" value="<?=$model['tlp']?>" placeholder="no Tlp/Hp" >
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="Forwarder[qq]" value="<?=$model['qq']?>" placeholder="QQ" >
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="Forwarder[wechat]" value="<?=$model['wechat']?>" placeholder="wechat" >
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
   
    </div>
        <hr class="light-grey-hr">
    
    <div class="form-actions">
        <div class="row">
            <div class="text-center col-md-12">
                <button type="submit" class="btn btn-success"><?=($model->isNewRecord ? 'Create' : 'Save'); ?></button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</form>

views/forwarder/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ForwarderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="forwarder-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'kd_fw') ?>

    <?= $form->field($model, 'nm_fw') ?>

    <?= $form->field($model, 'tlp') ?>

    <?= $form->field($model, 'qq') ?>

    <?php // echo $form->field($model, 'wechat') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/forwarder/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Forwarder */

$this->title = Yii::t('app', 'Create Forwarder');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Forwarders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="forwarder-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/forwarder/index.php
<?php
use yii\helpers\Html;
// use yii\grid\GridView;
use kartik\grid\GridView;

use yii\widgets\Pjax;
use app\models\Menu;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MaterialSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$link=Yii::$app->controller->id.'/'.Yii::$app->controller->action->id;
$menu=Menu::find()->where(['link'=>$link])->one();
$this->title = Yii::t('app', $menu->name); /*TITLE*/
$icon = Yii::t('app', '<i class="mdi '.$menu->icon.' fa-fw"></i>'); /*icon*/ /*<i class="mdi mdi-basket-unfill fa-fw"></i>*/
// $this->params['breadcrumbs'][] = $this->title;
?>

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title"><?=$icon?><?=$this->title?></h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        
        <ol class="breadcrumb">
            <?php
                if(isset($menu->parent)){
            ?>
                    <li class=""><?=$menu->parent->name?></li>
            <?php
                }
            ?>
            <li class="active"><?=$this->title?></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <h3 class="box-title">
                <?=$icon?> Kelola <?=$this->title?>

                <button class="add_fw btn  btn-success btn-icon-anim btn-circle pull-right" data-toggle="tooltip" data-original-title="Tambah <?=$this->title?>" data-placement="left">
                    <span class="ti-plus"></span> 
                </button>
            </h3>
             <hr>
            <div class="table-body">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- <div class="table-responsive"> -->
                          <?php Pjax::begin(); ?>    <?= GridView::widget([
                                    'tableOptions'=>['class'=>'table table-condensed table-hover '],
                                    'dataProvider' => $dataProvider,
                                    'filterModel' => $searchModel,
                                    'responsive'=>true,
                                    'responsiveWrap'=>false,
                                    'condensed'=>true,
                                    'bordered'=>false,
                                    'export'=>false,
                                    'columns' => [
                                        ['class' => 'yii\grid\SerialColumn'],

                                        // 'id',
                                        // 'kd_fw',
                                        'nm_fw',
                                        'tlp',
                                        'qq',
                                        'wechat',
                                        // 'created_at',

                                        [   
                                            'header'=>'<center><i class="fa fa-cogs"></i></center>',

                                            'class' => 'yii\grid\ActionColumn',
                                            'template'=>'<center>{update} {delete}</center>',
                                            'buttons'=>[
                                                'update'=>function($url,$model){
                                                    return '<button type="button" class="btn btn-primary btn-circle btn-sm update_fw" id="'.$model->id.'" data-toggle="tooltip" data-original-title="Update Forwarder" data-placement="top"><i class="fa fa-pencil"></i></button>';
                                                },
                                                'delete'=>function($url,$model){
                                                    return '<button type="button" class="btn btn-danger btn-circle btn-sm del_fw" id="'.$model->id.'" data-toggle="tooltip" data-original-title="Hapus Forwarder" data-placement="top"><i class="fa fa-trash"></i></button>';
                                                }
                                            ],
                                        ],
                                    ],
                                ]); ?>
                            <?php Pjax::end(); ?>
                                    <!-- 'tableOptions'=>['class'=>'table table-condensed table-hover'], -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/forwarder/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Forwarder */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Forwarder',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Forwarders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="forwarder-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/forwarder/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Forwarder */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Forwarders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="forwarder-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'kd_fw',
            'nm_fw',
            'tlp',
            'qq',
            'wechat',
            'created_at',
        ],
    ]) ?>

</div>