models/User.php
<?php

namespace app\models;
use yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
// class User extends \yii\base\Object implements \yii\web\IdentityInterface
class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    public static function tableName()
    {
        return 'user';
    }
    // public $id;
    // public $username;
    // public $password;
    // public $authKey;
    // public $accessToken;

    // private static $users = [
    //     '100' => [
    //         'id' => '100',
    //         'username' => 'admin',
    //         'password' => 'admin',
    //         'authKey' => 'test100key',
    //         'accessToken' => '100-token',
    //     ],
    //     '101' => [
    //         'id' => '101',
    //         'username' => 'demo',
    //         'password' => 'demo',
    //         'authKey' => 'test101key',
    //         'accessToken' => '101-token',
    //     ],
    // ];


    /**
     * @inheritdoc
     */
    public function getRole(){
        return $this->hasOne(Role::className(),['id'=>'id_role']);
    }

    public function getPermission(){
        return $this->hasMany(Permissions::className(),['role_id'=>'id_role']);
    }


    public static function findIdentity($id)
    {
        return static::findOne($id);        
        // return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        // foreach (self::$users as $user) {
        //     if ($user['accessToken'] === $token) {
        //         return new static($user);
        //     }
        // }

        // return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username'=>$username]);
        // foreach (self::$users as $user) {
        //     if (strcasecmp($user['username'], $username) === 0) {
        //         return new static($user);
        //     }
        // }

        // return null;
    }


    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        // return $this->password === $hash;
        return Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;




/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST','GET'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $user=Yii::$app->user->identity;
        $data=[];
        $data['user']=$user;
        $data['model']=$model;

        $r=Yii::$app->request->post('User');
        if ($r!= null) {
            $model->fullname=$r['fullname'];
            $model->username=$r['username'];
            $model->email=$r['email'];
            $model->password=Yii::$app->getSecurity()->generatePasswordHash($r['password']);
            $model->id_role=$r['id_role'];
            $model->authKey=Yii::$app->security->generateRandomString();
            $model->store_id=$user->store_id;
            if($model->save()){
                $pesan=['pesan'=>'Data Berhasil di tambahkan !','status'=>1];
            }else{
                $pesan=['pesan'=>'Data gagal di tambahkan !','status'=>0,'errors'=>'<pre>'.$e];
            }
            echo json_encode($pesan);
        } else {
            return $this->renderPartial('_form', $data);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $user=Yii::$app->user->identity;
        $data=[];
        $data['user']=$user;
        $data['model']=$model;

        $r=Yii::$app->request->post('User');
        if ($r!= null) {
            $model->fullname=$r['fullname'];
            $model->username=$r['username'];
            $model->email=$r['email'];
            $model->id_role=$r['id_role'];
            if($model->save()){
                $pesan=['pesan'=>'Data Berhasil di update !','status'=>1];
            }else{
                $pesan=['pesan'=>'Data gagal di di update !','status'=>0,'errors'=>'<pre>'.$e];
            }
            echo json_encode($pesan);
        } else {
            
            return $this->renderPartial('_form', $data);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        // return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/user/_form - Copy.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>


    <!-- <?= $form->field($model, 'authKey')->textInput(['maxlength' => true]) ?> -->

    <!-- <?= $form->field($model, 'accessToken')->textInput(['maxlength' => true]) ?> -->

    <!-- <?= $form->field($model, 'active')->textInput() ?> -->

    <?= $form->field($model, 'fullname')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'role')->textInput() ?>

    <!-- <?= $form->field($model, 'created_by')->textInput(['maxlength' => true]) ?> -->

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_form.php
<?php
    use yii\helpers\Url;
    use yii\helpers\Html;
    use yii\helpers\ArrayHelper;

    use app\models\Role;
?>

<form class="form-horizontal" id="form_user" action="<?=($model->isNewRecord) ? Url::toRoute('user/create') : Url::toRoute('user/update').'/'.$model['id']; ?>" role="form">
    <div class="form-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="User[fullname]" value="<?=$model['fullname']?>" placeholder="Nama Lengkap" required="required">
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="User[username]" value="<?=$model['username']?>" placeholder="username" required="required">
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="User[email]" value="<?=$model['email']?>" placeholder="email" required="required">
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <?php
            if($model->isNewRecord){
        ?>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="password" class="form-control" name="User[password]" value="<?=$model['password']?>" placeholder="password" required="required">
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
         <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                         <?=Html::DropDownList("User[id_role]",$model['id_role'],ArrayHelper::map(Role::find()->all(), 'id', 'fullname'),['id'=>'id_role','class'=>'form-control','required'=>'required','prompt'=>'-- Pilih Role --']);?>
                        <span class="help-block">
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <hr class="light-grey-hr">
    
    <div class="form-actions">
        <div class="row">
            <div class="text-center col-md-12">
                <button type="submit" class="btn btn-success"><?=($model->isNewRecord ? 'Create' : 'Save'); ?></button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</form>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'authKey') ?>

    <?= $form->field($model, 'accessToken') ?>

    <?php // echo $form->field($model, 'active') ?>

    <?php // echo $form->field($model, 'fullname') ?>

    <?php // echo $form->field($model, 'role') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
// use yii\grid\GridView;
use kartik\grid\GridView;

use yii\widgets\Pjax;
use app\models\Menu;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MaterialSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$link=Yii::$app->controller->id.'/'.Yii::$app->controller->action->id;
$menu=Menu::find()->with(['permit_action'])->where(['link'=>$link])->one();
$this->title = Yii::t('app', $menu->name); /*TITLE*/
$icon = Yii::t('app', '<i class="mdi '.$menu->icon.' fa-fw"></i>'); /*icon*/ /*<i class="mdi mdi-basket-unfill fa-fw"></i>*/
// $this->params['breadcrumbs'][] = $this->title;



$sess = Yii::$app->session;
$sess->set('current_action',$link);
$sess->set('menu',$menu);

?>

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title"><?=$icon?><?=$this->title?></h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        
        <ol class="breadcrumb">
            <?php
                if(isset($menu->parent)){
            ?>
                    <li class=""><?=$menu->parent->name?></li>
            <?php
                }
            ?>
            <li class="active"><?=$this->title?></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <h3 class="box-title">
                <?=$icon?>Kelola <?=$this->title?>
                <?php
                    foreach ($menu->permit_action  as $value) {
                        if($value->menu_action->tipe=='add'){
                            
                            echo '<button type="button" class="btn  btn-circle btn-sm pull-right '.$value->menu_action->class_add.'"  data-toggle="tooltip" data-original-title="'.ucwords($value->menu_action->name).'" data-placement="top"><i class="fa '.$value->menu_action->icon.'"></i></button>';
                        }
                    }
                ?>
            </h3>
             <hr>
            <div class="table-body">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- <div class="table-responsive"> -->
                          <?php Pjax::begin(); ?>    <?= GridView::widget([
                                'tableOptions'=>['class'=>'table table-condensed table-hover '],

                                'dataProvider' => $dataProvider,
                                'filterModel' => $searchModel,
                                'responsive'=>true,
                                'responsiveWrap'=>false,
                                'condensed'=>true,
                                'bordered'=>false,
                                'export'=>false,
                                'columns' => [
                                    ['class' => 'yii\grid\SerialColumn'],
                                    // Starter column
                                        // [
                                        //     'header'=> '',
                                        //     'format'=>'',
                                        //     'value'=>function($model,$key,$i){
                                        //         return '';
                                        //     },
                                        //     'filter'=>'<input type="text" class="form-control input-sm" name="" value="" placeholder="" >'
                                    //     // ],
                                    // 'id',
                                    // 'password',
                                    'username', 
                                    'fullname',
                                    'email',
                                    
                                    [
                                            'header'=> 'Role',
                                            'format'=>'raw',
                                            'value'=>function($model,$key,$i){
                                                return $model->role->fullname;
                                            },
                                            // 'filter'=>'<input type="text" class="form-control input-sm" name="" value="" placeholder="" >'
                                        ],
                                    // 'authKey',
                                    // 'accessToken',
                                    // 'active',
                                    // 'fullname:ntext',
                                    // 'role',
                                    // 'created_by',
                                    // 'created_at',
                                    // 'updated_at',

                                    // ['class' => 'yii\grid\ActionColumn'],
                                    [   'header'=>'<center><i class="fa fa-cogs"></i></center>',
                                        'headerOptions' => ['width' => '100'],

                                        'class' => 'yii\grid\ActionColumn',
                                        'template'=>'<center>{action}</center>', /*{update} {delete} */

                                        'buttons'=>[
                                            // 'update'=>function($url,$model){
                                            //     return '<button type="button" class="btn btn-primary btn-circle btn-sm update_user" id="'.$model->id.'" data-toggle="tooltip" data-original-title="Update User" data-placement="top"><i class="fa fa-pencil"></i></button>';
                                            // },
                                            // 'delete'=>function($url,$model){
                                            //     return '<button type="button" class="btn btn-danger btn-circle btn-sm del_user" id="'.$model->id.'" data-toggle="tooltip" data-original-title="Hapus User" data-placement="top"><i class="fa fa-trash"></i></button>';
                                            // },
                                            'action'=>function($url,$model) use ($menu) {
                                                $html="";
                                                foreach ($menu->permit_action  as $value) {
                                                    if($value->menu_action->tipe!='add'){

                                                        $html.='<button type="button" class="btn  btn-circle btn-sm '.$value->menu_action->class_add.'" id="'.$model[$value->menu_action->column_param].'" data-toggle="tooltip" data-original-title="'.ucwords($value->menu_action->name).'" data-placement="top"><i class="fa '.$value->menu_action->icon.'"></i></button>';
                                                    }
                                                }
                                                return $html;
                                            }
                                        ],
                                    ],
                                ],
                            ]); ?>
                        <?php Pjax::end(); ?>
                        <!-- </div> -->
                    </div>
                    <?php
                        // echo $sess->get('current_action');
                        // echo "<pre>";
                        // print_r($menu->permit_action);
                        // foreach ($menu->permit_action as $value) {
                        //     echo $value->menu->name.' => '.$value->menu_action->name."<br>";
                        // }
                        
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'User',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'password',
            'username',
            'authKey',
            'accessToken',
            'active',
            'fullname:ntext',
            'role',
            'created_by',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>