models/VOrders.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_orders".
 *
 * @property string $kd_order
 * @property integer $tipe_transfer
 * @property integer $tipe_transaksi
 * @property string $qty
 * @property string $ongkir_buyer
 * @property string $total_belanja
 * @property string $total_tagihan_buyer
 * @property string $buyer
 * @property string $buyer_note
 * @property string $id_market
 * @property integer $id_kurir
 * @property string $resi
 * @property integer $status
 * @property string $created_at
 * @property string $created_by
 */
class VOrders extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_orders';
    }

    public static function primaryKey(){
        return ["kd_order"];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kd_order', 'tipe_transfer', 'ongkir_buyer', 'buyer', 'buyer_note', 'id_market', 'id_kurir', 'resi', 'created_by'], 'required'],
            [['tipe_transfer', 'tipe_transaksi', 'ongkir_buyer', 'buyer', 'id_market', 'id_kurir', 'status', 'created_by'], 'integer'],
            [['qty', 'total_belanja', 'total_tagihan_buyer'], 'number'],
            [['buyer_note'], 'string'],
            [['created_at'], 'safe'],
            [['kd_order'], 'string', 'max' => 100],
            [['resi'], 'string', 'max' => 150],
        ];
    }
    // get MaterialDetail
    public function getMd(){
        return $this->hasMany(MaterialDetail::className(),['kd_order'=>'kd_order']);
    }
    // get buyer/pelanggan
    public function getPlg(){
        return $this->hasOne(Customers::className(),['id'=>'buyer']);
    }
     // get Created by
    public function getCsby(){
        return $this->hasOne(User::className(),['id'=>'created_by']);
    }
    // get market
    public function getMkt(){
        return $this->hasOne(Marketplace::className(),['id'=>'id_market']);
    }
    // get status
    public function getStatus(){
        return $this->hasOne(AppStatus::className(),['id'=>'id_status']);
    }
    // get kurir
    public function getKurir(){
        return $this->hasOne(Kurir::className(),['id'=>'id_kurir']);
    }
    // get v_material_stok
    public function getVmstok(){
        return $this->hasMany(VMaterialStok::className(),['kd_order'=>'kd_order']);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'kd_order' => 'Kd Tagihan',
            'tipe_transfer' => 'Tipe Transfer',
            'tipe_transaksi' => 'Tipe Transaksi',
            'qty' => 'Qty',
            'ongkir_buyer' => 'Ongkir Buyer',
            'total_belanja' => 'Total Belanja',
            'total_tagihan_buyer' => 'Total Tagihan Buyer',
            'buyer' => 'Buyer',
            'buyer_note' => 'Buyer Note',
            'id_market' => 'Id Market',
            'id_kurir' => 'Id Kurir',
            'resi' => 'Resi',
            'status' => 'Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
        ];
    }

    public static function salesthisyear(){
        $user=Yii::$app->user->identity;

        $sql="SELECT 
                mt.month_name,
                -- mt.month_field,
                -- IFNULL(tr.qty_sales,200000) qty,
                IFNULL(tr.total_sales,0) OMZET,
                IFNULL(tr.total_earnings,0) MARGIN
                FROM (
                    select 
                    DATE_FORMAT(date_field, '%m') month_only,
                    DATE_FORMAT(date_field, '%m-%Y') month_field,
                    DATE_FORMAT(date_field,'%b') month_name                    
                    from
                    (
                        select adddate('1970-01-01',t4*10000 + t3*1000 + t2*100 + t1*10 + t0) date_field from
                        (select 0 t0 union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t0,
                        (select 0 t1 union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t1,
                        (select 0 t2 union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t2,
                        (select 0 t3 union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t3,
                        (select 0 t4 union select 1 union select 2 union select 3 union select 4 union select 5 union select 6 union select 7 union select 8 union select 9) t4
                    ) t_date 
                    where  
                    YEAR(date_field) = YEAR(CURDATE())
                    GROUP BY DATE_FORMAT(date_field, '%m-%Y') ASC
                ) mt
                LEFT JOIN 
                (
                    SELECT 
                    SUM(qty_sales) qty_sales,
                    SUM(total_sales) total_sales,
                    SUM(total_earnings) total_earnings,
                    `month_field` 
                    FROM trval_this_year WHERE store_id=".$user->store_id." GROUP BY `month_field` 
                ) tr ON mt.month_field=tr.month_field";
        return Yii::$app->db->createCommand($sql)->queryAll();
    }
}

controllers/VordersController.php
<?php
namespace app\controllers;

use Yii;
use app\models\VOrders;
use app\models\VOrdersSearch;
use app\models\Customers;
use app\models\Marketplace;
use app\models\SalesThisWeek;
use app\models\SalesThisWeekByItem;
use app\models\SalesToday;
use app\models\ItemVarian;
use app\models\VMaterial;
use app\models\MasterMaterial;
use app\models\Top5sales;
use app\models\TrvalThisMonth;
use app\models\TrvalToday;
use app\models\User;
use app\models\MaterialDetail;
use app\models\StProvince;
use app\models\Kurir;

use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use app\components\Help;

/**
 * VordersController implements the CRUD actions for VOrders model.
 */
class VordersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all VOrders models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VOrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'user'=>Yii::$app->user->identity,
            'cm'=>ArrayHelper::map(Customers::find()->All(),'id','nama'),
            'mp'=>ArrayHelper::map(Marketplace::find()->where(['<>','id',100])->All(),'id','nm_market'),
        ]);
    }

    /**
     * Displays a single VOrders model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new VOrders model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new VOrders();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->kd_tagihan]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing VOrders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->kd_tagihan]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionSalesthisweek(){
        $user=Yii::$app->user->identity;
        $model=SalesThisWeekByItem::getChart();
        $chart=[];
        
        $var=ArrayHelper::getColumn(SalesThisWeekByItem::find()->where(['store_id'=>$user->store_id])->all(),'item');
        $key_chart=[];
        $label_chart=[];
        $color=[];
        $legend=[];

        foreach ($var as $item_name) {
            $key_chart[]=Help::toAlnumOnly($item_name);          
        }
        
        foreach ($model as $item) {
            $chart[$item['period_field']]['period']=$item['period_field'];
            if($item['item']!==null){
                foreach ($var as $varian) {
                    $a[Help::toAlnumOnly($varian).'_'.$item['period_field']]=0;      
                }
                $b[Help::toAlnumOnly($item['item']).'_'.$item['period_field']]=$item['qty'];
                foreach (array_replace($a,$b) as $key => $value) {
                    $key_arr=explode('_',$key);
                    if($key_arr[1]==$item['period_field']){
                        $chart[$item['period_field']][$key_arr[0]]=intval($value);
                    }
                }
            }else{
                foreach ($var as $varian) {                
                    $chart[$item['period_field']][Help::toAlnumOnly($varian)]=0;
                }
            }
        }
        foreach ($var as $item2) {
            $cl=Help::get_random_color();                
            $color[]=$cl;
            $legend[]="<li><h5><i class='fa fa-circle m-r-5' style='color: ".$cl."'></i>".$item2."</h5> </li>";
        }

        $chartfix=[];
        foreach ($chart as $key => $value) {
            $chartfix[]=$value;
        }

        $data=[];
        $data['data']=$chartfix;
        $data['keys']=$key_chart;
        $data['labels']=$var;
        $data['colors']=$color;
        $data['legends']=$legend;

        echo json_encode($data,JSON_PRETTY_PRINT);
    }

    public function actionSalesthisyear(){
        $user=Yii::$app->user->identity;
        $model=VOrders::salesthisyear();
        $field=array_keys($model[0]);
        $clean_field=array_diff($field,['month_field','month_name']);
        $data=[];
        $data['data']=$model;
        $data['xkey']='month_name';

        foreach ($clean_field as $item) {
            $cl=Help::get_random_color();                
            $color[]=$cl;
            $legend[]="<li><h5><i class='fa fa-circle m-r-5' style='color: ".$cl."'></i>".$item."</h5> </li>";
            $data['ykeys'][]=$item;
            $data['labels'][]=$item;
        }

        $data['colors']=$color;
        $data['legends']=$legend;

        echo json_encode($data,JSON_PRETTY_PRINT);

    }
    public function actionSalestoday(){
        $user=Yii::$app->user->identity;
        $model=TrvalToday::find()->where(['store_id'=>$user->store_id])->asArray()->all();
        $data=[];
        $chart=[];
        $color=[];

        foreach ($model as $item) {
            $chart_data['label']=$item['item'];
            $chart_data['value']=intval($item['qty_sales']);
            $chart[]=$chart_data;
            $color[]=Help::get_random_color();
        }

        $data['data']=$chart;
        $data['colors']=$color;

        // echo "<pre>";
        echo json_encode($data,JSON_PRETTY_PRINT);
    }

    public function actionTop5sales(){
        $user=Yii::$app->user->identity;
        $data=[];
        $data['models']=Top5sales::find()->where(['store_id'=>$user->store_id])->all();
        return $this->renderPartial('_top5sales',$data);
    }

    public function actionTrvalthismonth(){
        $user=Yii::$app->user->identity;
        $data=[];
        $data['models']=TrvalThisMonth::find()->where('qty_sales>0')->andWhere(['store_id'=>$user->store_id])->all();
        return $this->renderPartial('_trvalthismonth',$data);
    }

    /**
     * Deletes an existing VOrders model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    public function actionReport(){
        $data=[];
        $user=Yii::$app->user->identity;

        if(Yii::$app->request->isAjax){
            $start=date('Y-m-d',strtotime(Yii::$app->request->post('start')));
            $end=date('Y-m-d',strtotime(Yii::$app->request->post('end')));
            
            $where="(DATE(v_orders.done_at) BETWEEN '".$start."' AND '".$end."') ";

            if(Yii::$app->request->post('cs') !== null && Yii::$app->request->post('cs') !== ''){
                $where.=" AND v_orders.created_by=".Yii::$app->request->post('cs');    
            }

            $data['model']=VOrders::find()->where(['v_orders.store_id'=>$user->store_id])
            ->joinWith(['md'=>function($md){
                if(Yii::$app->request->post('item') !== null && Yii::$app->request->post('item') !== ''){
                    $md->joinWith('v_material')
                    ->where(['v_material.kode'=>Yii::$app->request->post('item')]);
                }
            }])
            ->where($where)->orderBy("v_orders.done_at DESC")->all();       

            return $this->renderPartial("_report",$data);

            // echo "<pre>";
            // print_r($data['model']);
        }else{
            $data['item']=ArrayHelper::map(MasterMaterial::find()->where(['store_id'=>$user->store_id])->all(),'kode','nama');
            $data['cs']=ArrayHelper::map(User::find()->where(['id_role'=>2,'store_id'=>$user->store_id])->all(),'id','fullname');
            return $this->render('report',$data);
        }  
    }


    public function actionCreate_od_dropship(){

        $model=new MaterialDetail;
        $user=Yii::$app->user->identity;
        $data=[];
        $data['user']=$user;
        $data['model']=$model;
        $md = Yii::$app->request->post('md');
        $cm = Yii::$app->request->post('customer');
        $qty = Yii::$app->request->post('qty');
        $inv = Yii::$app->request->post('inv');
        $hj = Yii::$app->request->post('hgsat_jual');
        $hgmod = Yii::$app->request->post('hgmod');
        // print_r($rq->bodyParams);
        // foreach ($md['id_material'] as $id_item) {
        //     echo $md['qty'][$id_item].'//';
        // }

        if($md!=null){
            $transaction=Yii::$app->db->beginTransaction();
            try {
                if($cm['id_c']==null || $cm['id_c']==''){
                    $c=new Customers;
                    $c->nama=ucwords(strtolower($cm['nama']));

views/vorders/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\VOrders */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vorders-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'kd_tagihan')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tipe_transfer')->textInput() ?>

    <?= $form->field($model, 'tipe_transaksi')->textInput() ?>

    <?= $form->field($model, 'qty')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ongkir_buyer')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'total_belanja')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'total_tagihan_buyer')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'buyer')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'buyer_note')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'id_market')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'id_kurir')->textInput() ?>

    <?= $form->field($model, 'resi')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/vorders/_form_bm_od.php
<?php
    use yii\helpers\Url;
    use yii\helpers\Html;

	$action=Yii::$app->controller->action->id;

    // \kartik\select2\Select2Asset::register($this);
?>
<form class="form-horizontal" id="form_odropship" role="form">

		<div class="form-group form-group-mat">

			<label class="col-md-3 control-label" style="text-align: left !important">Pilih barang </label>
			<div class="col-md-7">
			
				<?=Html::DropDownList("md[id]",null,$Barang,['id'=>'id_dropship','multiple'=>'multiple','class'=>'select2','required'=>'required','empty'=>'-- Pilih Barang --']);?>

				<span class="help-block pull-right">
					<!-- <a href="javascript:;" class="text-danger">Piih material dari lokasi lain ?</a> -->
				</span>
			</div>
			<div class="col-md-2">
				
			</div>
		</div>
	
		<div class="load_inout"></div>
		
	</div>
	<hr>
	<div class="form-actions">
		<div class="row">
			<div class="col-md-12 text-center">
				<button type="submit" class="btn  btn-success"><i class="fa fa-check"></i> Simpan</button>
				<button type="button" class="btn  btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Cancel</button>
			</div>
		</div>
	</div>
</form>

views/vorders/_form_od_edit.php
<form id="form_od_edit">
    <?php
    use yii\helpers\Html;
    use app\components\Help;


        foreach ($model->md as $od) {
    ?>  
        <input type="hidden" name="md_id[]" value="<?=$od->id?>">
         <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><?=$od->v_materialbyinv['kd_tagihan_view']?></span>

                        <b class="form-control"><?=$od->v_materialbyinv['fullname']?></b>
                        <span class="input-group-addon">Stok : <?=$od->v_materialbyinv['stok_akhir']?></span>
                    </div>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <input type="hidden" name="hgmod[<?=$od['id']?>]" value="<?=$od['harga_mod']?>">

                    <input type="text" id="hgsat_<?=$od['id']?>" placeholder="Harga satuan" name="hgsat_jual[<?=$od['id']?>]" class="form-control kal_or hgsat MaskMoney" required="required"  data-id="<?=$od['id']?>" value="<?=Help::toRp($od['hgsat_jual'])?>"> 

                </div>      
            </div>

            <div class="col-md-2">
               <div class="form-group">
                    <!-- <label class="col-md-1 control-label">QTY</label> -->
                        <input  id="qty_<?=$od['id']?>"  data-id="<?=$od['id']?>" type="text"  value="<?=$od['qty']?>" data-value="<?=$od['qty']?>" name="qty[<?=$od['id']?>]" class="touchspin" data-bts-button-down-class="btn btn-default btn-outline " data-bts-button-up-class="btn btn-default btn-outline" required="required" readonly="readonly" >
                        <span class="help-block">
                        </span>
                </div>
            </div>
        </div>

     <?php
        }
    ?>
    <hr>
        <div class="row">
            <div class="col-md-6">
               <div class="form-group">
                    <div class="input-group" >
                        <span class="input-group-addon" style="background: white">Pelanggan</span>
                        <?=Html::DropDownList('md[id_c]',$model->plg->id,$Customers,['id'=>'c_id','class'=>'form-control select2','prompt'=>'-- Pilih Pelanggan --'])?>

                    </div>
               </div>
            </div>

           

            <div class="col-md-6">
               <div class="form-group">
                    <div class="input-group" >
                        <span class="input-group-addon" style="background: white">Marketplace</span>
                        <?=Html::DropDownList("md[id_market]", $model->mkt->id,$Market,['id'=>'id_market','class'=>'form-control select2','prompt'=>'-- Pilih Marketplace --']);?>
                    </div>
               </div>
            </div>
        </div>
        <div class="row">
             <div class="col-md-6">
               <div class="form-group">
                    <div class="input-group" >
                        <span class="input-group-addon" style="background: white">Kurir</span>
                        <?=Html::DropDownList("md[id_kurir]", $model->kurir->id,$Kurir,['id'=>'id_kurir','class'=>'form-control select2','data-allow-clear'=>true,'prompt'=>'-- Pilih Kurir --']);?>
                    </div>
               </div>
            </div>
            <div class="col-md-6">
               <div class="form-group">
                    <div class="input-group" >
                        <span class="input-group-addon" style="background: white">Biaya kirim</span>
                        <input type="text" id="ongkir_buyer" placeholder="Biaya kirim" name="md[ongkir_buyer]" class="form-control MaskMoney kal_or" value="<?=Help::toRp($od->ongkir_buyer);?>"  > 

                    </div>
               </div>
            </div>

        </div>
    <hr>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-12 text-center">
                <button type="submit" class="btn  btn-success"><i class="fa fa-check"></i> Simpan</button>
                <button type="button" class="btn  btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Cancel</button>
            </div>
        </div>
    </div>
</form>

views/vorders/_report.php
<?php
use app\components\Help;
?>
<table class="table table-bordered">
		
	<thead>
		<tr>
			<th><i class="fa fa-user fa-fw"></i>CS</th>
			<th>Marketplace</th>
			<th>Tgl & waktu</th>
			<th>Barang</th>
			<th>(QTY) Varian </th>
			<th>Omzet</th>
			<th>Margin</th>
			
		</tr>
		
	</thead>
	<tbody>
	<?php
		$no=1;
		foreach ($model as $data) {
	?>
		<tr>
			<td><b><?=$data->csby->fullname;?></b></td>
			<td><?=$data->mkt->nm_market?></td>
			<td><?=Help::datetimeindoShort($data->created_at);?></td>
			<td>
				<?php
					$arr=[];

                    foreach ($data->md as $item) {
                        $arr[]='<i class="fa fa-circle fa-fw" style="color:'.$item->v_material->kode_warna.'"></i>'.$item->v_material->nama;
                    }
                   
                    echo implode(array_unique($arr), '<br>');
				?>
			</td>
			<td>
				<?php
					$val='';
                    foreach ($data->md as $item) {
                        $val.='<i class="fa fa-chevron-right fa-fw" style="color:'.$item->v_material->kode_warna.'"></i>';
                        $val.='('.$item['qty'].') '.$item->v_material->varianname.' <br>';
                    }
                    echo $val;
				?>
			</td>
			<td><?=Help::toRp($data->total_belanja)?></td>
			<td><?=Help::toRp($data->total_margin)?></td>
		</tr>
	<?php
			$no++;
		}
	?>
	</tbody>

</table>

views/vorders/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\VOrdersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vorders-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'kd_tagihan') ?>

    <?= $form->field($model, 'tipe_transfer') ?>

    <?= $form->field($model, 'tipe_transaksi') ?>

    <?= $form->field($model, 'qty') ?>

    <?= $form->field($model, 'ongkir_buyer') ?>

    <?php // echo $form->field($model, 'total_belanja') ?>

    <?php // echo $form->field($model, 'total_tagihan_buyer') ?>

    <?php // echo $form->field($model, 'buyer') ?>

    <?php // echo $form->field($model, 'buyer_note') ?>

    <?php // echo $form->field($model, 'id_market') ?>

    <?php // echo $form->field($model, 'id_kurir') ?>

    <?php // echo $form->field($model, 'resi') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/vorders/_top5sales.php
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#RANK</th>
                <th>PRODUCT</th>
                <th>SOLD</th>
            </tr>
        </thead>
        <tbody>
            <?php
                $rank=1;
                foreach ($models as $key => $model) {
                    if($key==0){
                        $class="label-success";
                    }elseif ($key==1) { 
                        $class="label-info";
                    }elseif ($key==2) {
                        $class="label-primary";
                    }elseif ($key==3) {
                        $class="label-warning";
                    }elseif ($key==4) {
                        $class="label-danger";
                    }
            ?>
                    <tr>
                        <td style="width: 1%">#<?=$rank?></td>
                        <td class="txt-oflo"><?=$model['item']?></td>
                        <td>
                            <span class="label <?=$class?> label-rouded"><?=$model['sold']?></span> 
                        </td>
                    </tr>
            <?php
                $rank++;
                }
            ?>
            
        </tbody>
    </table>
</div>

views/vorders/_trvalthismonth.php
<?php
    use app\components\Help;
?>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#NO</th>
                <th>PRODUCT</th>
                <th>QTY</th>
                <th>TOTAL OMZET</th>
                <th>TOTAL MARGIN</th>
            </tr>
        </thead>
        <tbody>
            <?php
                $rank=1;
                foreach ($models as $key => $model) {
              
            ?>
                    <tr>
                        <td style="width: 1%"><?=$rank?></td>
                        <td class="txt-oflo"><?=$model['item']?></td>
                        <td>
                            <span class="label label-success label-rouded"><?=$model['qty_sales']?></span> 
                        </td>
                        <td class="txt-oflo"><?=Help::toRp($model['total_sales'])?></td>
                        <td class="txt-oflo"><?=Help::toRp($model['total_earnings'])?></td>
                    </tr>
            <?php
                $rank++;
                }
            ?>
            
        </tbody>
    </table>
</div>

views/vorders/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\VOrders */

$this->title = Yii::t('app', 'Create Vorders');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Vorders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vorders-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/vorders/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\VOrders */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Vorders',
]) . $model->kd_tagihan;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Vorders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->kd_tagihan, 'url' => ['view', 'id' => $model->kd_tagihan]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="vorders-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>